name: Build and test application
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!README.md'
      - '!docs/**'
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!README.md'
      - '!docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ libgtest-dev cmake libboost-system-dev libboost-date-time-dev

      - name: Create Build Directory
        run: mkdir build

      - name: Configure CMake
        run: |
          cd build
          cmake ..

      - name: Build
        run: cd build && make

      - name: Run tests
        run: ./build/test_project